PUT http://localhost:3003/api/blogs/5d6ed2d1e03eec535ff5a3da
Content-Type: application/json

# Change likes to whatever
{
    "title": "How to do things",
    "author": "Larry Garry",
    "url": "http://www.weeee.com",
    "likes": 4444,
    "id": "5d6addf9108930150c69896a"
}